[package]
name = "correlation_vector"
version = "0.1.0"
authors = ["ZiÎ»a Sarikaya <sarikayaziya@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2"
num-traits = "0.2"
num-derive = "0.2"
rand = "0.6"
